### PR TITLE
remove movies references, closes #42

### LINKED ISSUE #42: Cambiar documentación para centrarse en series
En la documentación se habla de películas y series, pero ahora que la aplicación se centrará en series habría que reformular la documentación, updates #8

### PR DESCRIPTION
**Pull request by Torchu**
remove movies references, closes #42

### CODE REVIEW

**Comment by JJ** [comment]
Yo should always refer to issues and/or user stories in a PR. No advacement in code or report without adding value to the client.

**Comment by Torchu** [comment]
> Yo should always refer to issues and/or user stories in a PR. No advacement in code or report without adding value to the client.

Sorry, I forgot to link the issue

**Comment by JJ** [comment]
Closes in the PR body, please?

**Comment by Torchu** [comment]
> Closes in the PR body, please?

Since I'm squashing the commits, shouldn't be better to close in the squash commit message?

**Comment by JJ** [comment]
> > Closes in the PR body, please?
> 
> Since I'm squashing the commits, shouldn't be better to close in the squash commit message?

This has nothing to do with the mechanism for closing. It's only that putting it in the body makes the issue active, and I can navigate to it by clicking. Also there will be a reference to this there.

**Comment by JJ** [comment]
Also, PRs are always part of a milestone.

**Review by JJ — APPROVED** [review]
En el momento que asignes esto a un milestone, está bien. Los PRs con un ámbito pequeño y bien enfocados son perfectos.

**Pull request merged**
