### PR TITLE
Show list

### LINKED ISSUE #40: Lista de series
- Proveer una lista de series al usuario
- Poder ver la información respecto a una serie

### PR DESCRIPTION
**Pull request by Torchu**
Shows a list of shows, updates #36, closes #40

- Sets up flask
- Adds Show class
- Adds show service
- Adds documentation

### CODE REVIEW

**Comment by JJ** [comment]
Please remember to *always* work towards a MVP in a milestone, and addressing some user story through the issues that describe the problems you have.

**Comment by Torchu** [comment]
In this case it shows a list of shows to advance #36 . In that HU the user asks to review shows, so they need a list of shows for that reviews.

**Comment by JJ** [comment]
> In this case it shows a list of shows to advance #36 . In that HU the user asks to review shows, so they need a list of shows for that reviews.

Whatever, you need to link the milestone here (and check that it matches what you're doing here)

**Comment by Torchu** [comment]
> > In this case it shows a list of shows to advance #36 . In that HU the user asks to review shows, so they need a list of shows for that reviews.
> 
> Whatever, you need to link the milestone here (and check that it matches what you're doing here)

I've linked the PR with the milestone too in the sidebar.

**Comment by JJ** [comment]
I would say this needs to be left on hold (possibly as a draft) until #45 (and its corresponding milestone) have been cleared.

**Pull request merged**
