### PR TITLE
Setup front

### LINKED ISSUE #69: Set up front
Sets up a front-end, document the framework decision and implement the CI for it.

### PR DESCRIPTION
**Pull request by Torchu**
- [x] Crea una aplicación dummy en angular
- [x] Configura el lint
- [x] Configura los tests
- [x] Crea una github action para la integración continua
- [x] Documenta la elección del framework

closes #69

### CODE REVIEW

**Comment by Torchu** [comment]
He añadido también la configuración para tener prettier como formateador de código. La gente suele añadirlo al gitignore, pero igual tiene sentido subirlo 🤔

**Comment by JJ** [comment]
It's entirely too early to decide on angular.
All PRs should be in a milestone. They should refer to issues, and user stories.
We're not even decided on a correct modelization of the problem, we can't even start to decide on a two-tier architecture.
Please try to cut scope to the milestone we're in, which is essentially setting up infrastructure.

**Comment by Torchu** [comment]
> It's entirely too early to decide on angular.
> All PRs should be in a milestone. They should refer to issues, and user stories.
> We're not even decided on a correct modelization of the problem, we can't even start to decide on a two-tier architecture.
> Please try to cut scope to the milestone we're in, which is essentially setting up infrastructure.

So, should I work in the back-end only?

**Comment by JJ** [comment]
No, you should create a sensible set of minimally viable product built on top of each other. Also justify technical elections before you actually commit to them. Angular might or might not be a good choice; but  it's not even close to a minimally viable product. Front-end functionality should be available and tested before you choose a framework. Eventually, you might need none, or you might simply have no time for the front-end.

**Comment by Torchu** [comment]
> No, you should create a sensible set of minimally viable product built on top of each other. Also justify technical elections before you actually commit to them. Angular might or might not be a good choice; but it's not even close to a minimally viable product. Front-end functionality should be available and tested before you choose a framework. Eventually, you might need none, or you might simply have no time for the front-end.

So you're saying is way too early to be thinking in front-end? I'm used to build front-end and back-end at the same time to have a better perspective of what a client would want, but I can close this PR and come back to this in a later stage

**Comment by JJ** [comment]
Well, milestones are milestones, so you have to reach one before going on to the other. Right now [this one](https://github.com/Torchu/flixbuff/milestone/1) is 45% done. You should try and reach that milestone before going on to the next. This PR does not even have a milestone; that should tell you something.
A methodology for developing is mainly about two things: what do I do next, is what I'm doing OK. This PR fails on both counts. Does not refer to an issue so we don't know if we're doing it right or not, it is not what we need to do next, because it's not even in a milestone. Methodology is not something you write as a chapter in the report, is something you need to follow.
That said, you might need it later, when you reach that milestone, or not. Just leave it there, when we actually need it we might decide to rewrite it completely, reuse it or whatever.

**Comment by Torchu** [comment]
> Well, milestones are milestones, so you have to reach one before going on to the other. Right now [this one](https://github.com/Torchu/flixbuff/milestone/1) is 45% done. You should try and reach that milestone before going on to the next. This PR does not even have a milestone; that should tell you something.
> A methodology for developing is mainly about two things: what do I do next, is what I'm doing OK. This PR fails on both counts. Does not refer to an issue so we don't know if we're doing it right or not, it is not what we need to do next, because it's not even in a milestone. Methodology is not something you write as a chapter in the report, is something you need to follow.
> That said, you might need it later, when you reach that milestone, or not. Just leave it there, when we actually need it we might decide to rewrite it completely, reuse it or whatever.

Okay, I'll change the PR to a draft until we can give it an use.

**Comment by Torchu** [comment]
closes #69

**Pull request merged**
